name: Auto-cancel (Fork)
on: pull_request

jobs:
  cancel:
    name: Auto cancel earlier runs
    if: github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest

    steps:
      - uses: fauguste/auto-cancellation-running-action@0.1.4
        with:
          githubToken: ${{ github.token }}
